steps:
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'build'
  - '-t'
  - 'gcr.io/$PROJECT_ID/wetc-item-configurator-server-rs:latest'
  - '-f'
  - 'Dockerfile'
  - '.'
- name: 'gcr.io/cloud-builders/docker'
  args:
  - 'push'
  - 'gcr.io/$PROJECT_ID/wetc-item-configurator-server-rs:latest'
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'run'
  - 'deploy'
  - 'wetc-item-configurator-server-rs'
  - '--image'
  - 'gcr.io/$PROJECT_ID/wetc-item-configurator-server-rs:latest'
  - '--region'
  - 'us-central1'
  - '--port'
  - '9090'
images: ['gcr.io/$PROJECT_ID/wetc-item-configurator-server-rs:latest']
timeout: '2100s'
options:
  logging: CLOUD_LOGGING_ONLY
